<?
$title = "Terms of Use";
$custom_meta = '
<meta name="keywords" content="Rockchain, Terms of Use, Terms and Conditions" />
<meta name="description" content="Terms and Conditions governing the use of any and all Services provided by Rockchain Limited." />
<meta name="robots" content="index, follow" />';

$custom_og = '
<meta property="og:url" content="https://www.rockchain.com/"/>
<meta property="og:title" content="Terms of Use"/>
<meta property="og:description" content="Terms and Conditions governing the use of any and all Services provided by Rockchain Limited." />';
?>
<?php include 'header.php'; ?>
<section class="section-hero hero-small-illustration hero-illustration-1">
	<div class="container section-hero__container">
		<?php include 'menu.php'; ?>
		<h1 class="heading-1"><span class="highlight">Terms of Use - </span> Rockchain Services</h1>
	</div>
</section>
<section class="section-white">
	<div class="container section-white__container">
These Terms of Use ("Agreement") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and Rockchain Limited (“Rockchain”, "we", "us" or "our"), concerning your access to and use of the Rockchain websites (including but not limited to the Rockchain.com website, Rockproof.io website and tokentransparency.net website) or related content or applications including any application programming interface (“API”) and the Rockproof, Token Transparency Service and/or any other or associated Rockchain services (each a ‘Rockchain Service’ and together the ‘Services’). 
<br /><br />
Rockchain reserves the right, in its sole discretion, to modify this Agreement at any time by posting a notice to its website or by sending you a notice via email. You shall be responsible for reviewing any such modifications, and your use of the applicable Rockchain Service(s) following such notification constitutes your acceptance of the terms and conditions of this agreement as modified.
<br /><br />
We last updated our Terms & Conditions on 30th January 2019.
<br /><br />
<br />
<strong>1. CAPACITY and ELIGIBILITY.</strong> You are solely responsible for ensuring that this Agreement is in compliance with all laws, rules and regulations applicable to you, and you further represent and warrant that you have the full power and authority to enter into this Agreement and in doing so will not violate any other agreement to which you are a party. The right to access Rockchain’s Services is revoked where this Agreement or the use of Rockchain’s Services is prohibited or to the extent the offering, sale or provision of Rockchain’s Services conflicts with any applicable law, rule or regulation.
<br /><br />
<strong>2. REGISTRATION.</strong> To use Rockchain’s Services, you may be required to register for an account with Rockchain (an “Account”). You must provide accurate and complete information and keep your Account information updated. You are solely responsible for the activity that occurs on your Account, and for keeping your Account password secure. You may never use another person’s user account or registration information without permission. You must notify Rockchain immediately of any change in your eligibility to use Rockchain’s Services, or of any discovered or otherwise suspected breach of security or unauthorized use of your Account.
<br /><br />
<strong>3. GENERAL CONTENT DISCLAIMER.</strong> Postings on our websites are made at such times as Rockchain determines in its discretion. You should not assume that the information contained on our websites has been updated or otherwise contains current information. Rockchain does not review past postings to determine whether they remain accurate and information contained in such postings may have been superseded. THE INFORMATION AND MATERIALS IN/ON OUR WEBSITES ARE PROVIDED FOR YOUR REVIEW IN ACCORDANCE WITH THE NOTICES, TERMS AND CONDITIONS SET FORTH HEREIN. THESE MATERIALS ARE NOT GUARANTEED OR REPRESENTED TO BE COMPLETE, CORRECT OR UP TO DATE. THESE MATERIALS MAY BE CHANGED FROM TIME TO TIME WITHOUT NOTICE.
<br /><br />
<strong>4. POLICIES DISCLAIMER:</strong> WHERE WE OFFER YOU POLICY DOCUMENTS ("POLICIES"), YOU ACKNOWLEDGE THAT THESE POLICIES ARE PROVIDED TO HELP YOU WITH YOUR OVERALL COMPLIANCE GOALS AN ON AN AS-IS BASIS ONLY. WHILE THEY REPRESENT USEFUL INFORMATION AS A STARTING POINT, WE DO NOT CERTIFY OR GUARANTEE THAT THEY ARE APPROPRIATE FOR ANY SPECIFIC USE-CASE. THEY ARE DESIGNED AS AN AID ONLY TO DEVELOPING APPROPRIATE POLICIES TO HELP YOUR BUSINESS AND TO ADDRESS RELATED ISSUES FOR COMMERCIAL OR REGULATORY REASONS. WE CANNOT AND DO NOT GUARANTEE ANY CONFORMITY WITH APPLICABLE LAW AND THEY ARE NOT DESIGNED TO BE USED WITHOUT LEGAL ADVICE AND YOU ARE STRONGLY RECOMMENDED TO SEEK LEGAL ADVICE IN ADOPTING AND IMPLEMENTING SUCH POLICIES. WE ARE NOT LIABLE FOR ANY CONTENT, CODE, OR OTHER ERRORS OR OMISSIONS OR INACCURACIES. OUR WEBSITE PROVIDES NO WARRANTIES OR GUARANTEES. NOTHING IN THIS WEBSITE, THEREFORE, SHALL BE CONSIDERED LEGAL ADVICE AND NO LAWYER/ATTORNEY-CLIENT RELATIONSHIP IS ESTABLISHED. PLEASE NOTE THAT FURTHER ACTIONS MAY BE REQUIRED TO MAKE YOUR BUSINESS COMPLIANT WITH APPLICABLE LAW OR SPECIFIC REGULATORY REQUIREMENTS. 
<br /><br />
<strong>5.  LICENSE.</strong> Subject to your compliance with the terms and conditions of this Agreement, Rockchain hereby grants you a non-exclusive, non-sublicensable and non-transferable license to use Rockchain’s Services solely in accordance with any applicable documentation made available to you and solely for the purpose of developing and implementing applications that communicate with and make use of the Rockchain Services (each, an “Application”). Each end user of an Application shall be subject to (and you shall use commercially reasonable efforts to enforce) such Application's standard terms of service, which shall be consistent with, and at least as protective of Rockchain, as this Agreement. Rockchain reserves the right to impose limits on certain features and services of Rockchain’s Services, and limit your access to and use of the API for any reason, without notice or liability. Rockchain may also modify or discontinue offering the API at any time.
<br /><br />
<strong>6. RESTRICTIONS.</strong><br />
6.1 You may not use Rockchain’s Services to create any product or service that is competitive (in any way) with Rockchain’s Services or that seeks to resell Rockchain’s Services or any content or component related thereto.
<br /><br />
6.2 You may not use Rockchain’s Services in any manner, or to build any Application, that violates any law, rule or regulation, including without limitation for any purpose related to illegal gambling, fraud, money-laundering, or terrorist activities.
<br /><br />
6.3 You may not decompile, reverse engineer, disassemble, modify or create derivative works of Rockchain’s Services.
<br /><br />
6.4 You may not rent or lease Rockchain’s Services, or otherwise use Rockchain’s Services for the benefit of third parties.
<br /><br />
6.5 You may not perform or publish comparisons or other “benchmarking” activities with respect to Rockchain’s Services, either alone or in connection with any software.
<br /><br />
<strong>7. THIRD PARTY SERVICES.</strong> Rockchain’s Services may permit you to view content or link to or otherwise utilize other websites, services, software, tools or resources on the Internet (“Third Party Services”). You are solely responsible for complying with all terms and restrictions applicable to Third Party Services. You acknowledge that Rockchain is not responsible or liable for any Third Party Services, or any damage or loss you may incur in connection with your use of or reliance on Third Party Services.
<br /><br />
<strong>8. USER FEEDBACK.</strong><br />
8.1 As between the parties, all title, ownership rights, and intellectual property rights in and to Rockchain’s Services, and any copies or portions thereof, shall remain in Rockchain and its suppliers or licensors. Rockchain’s Services are protected by the intellectual property rights of Gibraltar and Europe and international copyright treaties. Rockchain reserves all rights in Rockchain’s Services not expressly granted herein.
<br /><br />
8.2 You may provide input regarding Rockchain’s Services,including without limitation comments or suggestions regarding the possible improvement or enhancement of Rockchain’s Services(collectively, the “Feedback”). You hereby grant to Rockchain a transferable, perpetual, irrevocable, worldwide, royalty-free license, with the right to sublicense to Rockchain’s licensees and customers, to use, publish, disclose, display, perform, copy, make, have made, use, sell, and otherwise fully exploit the Feedback. Rockchain shall be entitled to use Feedback for any purpose without restriction or remuneration of any kind.
<br /><br />
<strong>9. SUPPORT SERVICES.</strong> Rockchain shall have no obligation under this Agreement to provide any upgrades, patches, enhancements, fixes or any other support to you for Rockchain’s Services. You may contact Rockchain support through our website, but Rockchain does not make any promise or guarantee it will be able to fix any problem you may be having. If Rockchain provides you with any upgrades, patches, enhancements, or fixes for Rockchain’s Services, then the items that are provided will become part of Rockchain’s Services and subject to this Agreement. Any suggestions by Rockchain regarding Rockchain’s Services shall not be construed as a warranty.
<br /><br />
<strong>10. WARRANTY AND DISCLAIMER.</strong>TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, AND EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY ROCKCHAIN, ROCKCHAIN PROVIDES ROCKCHAIN’S SERVICES “AS IS” AND “AS AVAILABLE” AND WITHOUT WARRANTY OF ANY KIND, AND ROCKCHAIN HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, PERFORMANCE, ACCURACY, RELIABILITY, AND NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, WE DO NOT REPRESENT OR WARRANT THAT THE INFORMATION ON OR RELATED TO THE SERVICES YOU MAY USE OR PURCHASE IS ACCURATE, COMPLETE, RELIABLE, USEFUL, TIMELY OR CURRENT OR THAT OUR SERVICES WILL OPERATE WITHOUT INTERRUPTION OR ERROR. WE SHALL NOT HAVE ANY LIABILITY OR RESPONSIBILITY FOR ANY ERRORS OR OMISSIONS IN THE PROVISION OF OUR SERVICES, FOR YOUR ACTION OR INACTION IN CONNECTION WITH OUR SERVICES OR FOR ANY DAMAGE TO YOUR COMPUTER OR DATA OR ANY OTHER DAMAGE YOU MAY INCUR IN CONNECTION WITH OUR SERVICES. YOUR USE OF OUR SERVICES ARE AT YOUR OWN RISK. ROCKCHAIN, AND ITS DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, PARTNERS AND CONTENT PROVIDERS DO NOT WARRANT THAT: (I) ROCKCHAIN ’S SERVICES WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (II) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (III) ROCKCHAIN ’S SERVICES ARE OR WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (IV) THE RESULTS OF USING ROCKCHAIN ’S SERVICES WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS. ANY CONTENT OR INFORMATION YOU STORE OR TRANSFER THROUGH ROCKCHAIN ’S SERVICES MAY BECOME PERMANENTLY LOST OR CORRUPTED OR TEMPORARILY UNAVAILABLE FOR A VARIETY OF REASONS, INCLUDING WITHOUT LIMITATION INTERNET OUTAGES, PROTOCOL CHANGES BY THIRD PARTIES, FORCE MAJEURE EVENTS, SOFTWARE FAILURES, SCHEDULED OR UNSCHEDULED MAINTENANCE, OR OTHER CAUSES WITHIN OR BEYOND OUR CONTROL. YOUR USE OF ROCKCHAIN ’S SERVICES IS SOLELY AT YOUR OWN RISK.
<br /><br />
<strong>11. INDEMNITY.</strong>You agree that Rockchain shall have no liability whatsoever for any use you make of Rockchain ’s Services. You hereby agree to indemnify and hold harmless Rockchain from any and all claims, demands, damages, losses, liabilities, costs, and expenses (including legal fees) arising from or related to your use of Rockchain’s Services or any Application.
<br /><br />
<strong>12. LIMITATION OF LIABILITY.</strong> UNDER NO CIRCUMSTANCES SHALL ROCKCHAIN, NOR ITS DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS OR CONTENT PROVIDERS, BE LIABLE TO YOU OR ANY OTHER PERSON UNDER ANY LEGAL OR EQUITABLE THEORY (WHETHER UNDER TORT, CONTRACT, STRICT LIABILITY, NEGLIGENCE OR OTHERWISE) FOR: (A) INDIRECT, SPECIAL, INCIDENTAL, COMPENSATORY, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER (HOWEVER ARISING), EVEN IF FORESEEABLE, INCLUDING, WITHOUT LIMITATION, COST OF SUBSTITUTE TECHNOLOGY, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, LOSS OF DATA, COMPUTER FAILURE OR MALFUNCTION, BUGS, VIRUSES, TROJAN HORSES OR THE LIKE (REGARDLESS OF THE SOURCE OF ORIGINATION); (B) DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) THE GREATER OF (I) GBP 50.00 OR (II) THE AMOUNTS PAID BY YOU TO ROCKCHAIN WITH RESPECT TO ROCKCHAIN'S SERVICES DURING THE 12 MONTH PERIOD PRECEDING THE APPLICABLE CLAIM; OR (C) MATTERS BEYOND THEIR REASONABLE CONTROL.
<br /><br />
<strong>13. CONFIDENTIALITY.</strong> You will not disclose (or allow access to) to any third party any information which Rockchain protects against unrestricted disclosure to others, including without limitation the following information related to Rockchain’s Services: (a) computer software (object and source code), programming techniques and programming concepts, methods of processing, system designs embodied in the API; (b) benchmark results, program listings, data structures, logic diagrams, functional specifications, file formats; (c) system infrastructure, security/architecture design and/or operations processes; and (d) discoveries, inventions, concepts, designs, flow charts, documentation, product specifications, application program interface specifications, techniques and processes relating to Rockchain’s Services (collectively, “Confidential Information”). You will limit access to Rockchain’s Services (and any derived information) to your employees and consultants who are developing Applications on your behalf.
<br /><br />
<strong>14. PRIVACY.</strong> You are hereby deemed to have read and accepted our <a href="/privacy">privacy policy</a>.
<br /><br />
<strong>15. TERMINATION.</strong> You may terminate this Agreement and the license granted herein at any time by deleting your Account. Rockchain may terminate this Agreement and the license granted herein immediately if you breach any provision of this Agreement, for any other reason, or for no reason. Upon receiving notice of termination from Rockchain, you agree to destroy or remove from such storage media all copies of any documentation you received in connection with Rockchain’s Services. Sections 1, 2, 3, 4, 8, 9 ,10, 11, 12, 13, 14, 15 and 16 shall survive termination of this Agreement.
<br /><br />
<strong>16. GENERAL MATTERS.</strong> You shall not assign or transfer any part of this Agreement to any third party. This Agreement represents the complete agreement concerning this license between the parties and supersedes all prior agreements and representations between them, and, except as otherwise expressly set forth herein, may be amended only by a writing executed by both parties. If any provision of this Agreement is held to be unenforceable for any reason, such provision shall be reformed only to the extent necessary to make it enforceable. This Agreement will be governed by, and interpreted in accordance with, the laws of England and Wales and the Recipient hereby consents to submitting to the exclusive jurisdiction of Gibraltar in all matters regarding it except to the extent that Rockchain invokes the jurisdiction of the Courts of any other country for the purposes of enforcement.
</div>
</section>
<?php include 'footer.php'; ?>